version: '3.8'

services:
  app:
    image: 6fe1dbeea6876dd1c03a7bae0b56a11d2274204c3a8a89e4fa423c5208467645
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL:jdbc: jdbc:mysql://host.docker.internal:3306/customerdb?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerdb


